### PR TITLE
feat(cli): cli updated to use typescript

### PR DESCRIPTION
**Pull request by victordantasdev**
As suggested by @sibelius, the CLI is now written in TypeScript.

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
Should we commit or ignore lib compiled code?

**Comment by victordantasdev** [comment]
I don't know why the tests aren't running, and I can't believe I'm gonna say this, but on my machine runs with no problems.

image

**Comment by sibelius** [comment]
image

**Comment by victordantasdev** [comment]
> Should we commit or ignore lib compiled code?

Acho que não, pois para o node rodar uma CLI ele precisa de um binário em .js

**Comment by sibelius** [comment]
We can ignore, and have a prerelease commit to get it for the npm release

**Comment by victordantasdev** [comment]
> image

But i added `@types/jest` in `package.json`

image

**Comment by sibelius** [comment]
Weird

**Comment by sibelius** [comment]
Send it in a tweet asking for help

**Comment by victordantasdev** [comment]
I believe a possible answer to this problem is that the `@types/jest` is not in the `main` and the CI is running with the "old" `package.json`

**Pull request merged**
