### PR TITLE
chore: add application description to webmanifest

### PR DESCRIPTION
**Pull request by EternalQuasar0206**
## Implemented description in site.webmanifest

Description is good to SEO and may appear on Google search 😳

```
cc @sseraphini connects developers and technology people in an environment where 
everyone can ask their questions and learn in public without having to worry about external 
factors in a win-win relationship.
```

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
what about next head?

**Comment by EternalQuasar0206** [comment]
> what about next head?

Do we have any index.html?

**Comment by sibelius** [comment]
https://github.com/sibelius/ccsseraphini/blob/main/apps/web/src/components/Head.tsx#L7

**Comment by EternalQuasar0206** [comment]
> https://github.com/sibelius/ccsseraphini/blob/main/apps/web/src/components/Head.tsx#L7

Almost certain that will not work as excepted. I dont have property in Next, but this is a dynamic generated head, Google requires a static head to deal with SEO questions

**Pull request merged**
