### PR TITLE
feat: Render tweets images

### PR DESCRIPTION
**Pull request by danielcti**
Render tweets images (issue #131 )

image
image

### CODE REVIEW

**Review by biantris — APPROVED** [review]
Good

**Review by sibelius — APPROVED** [review]
Is this responsive?

**Comment by sibelius** [comment]
The missing part now is the link preview using og tags

**Comment by danielcti** [comment]
> The missing part now is the link preview using og tags

what does it mean?

**Comment by sibelius** [comment]
Check tweets with links, they have a preview of the link

**Pull request merged**
