### PR TITLE
feat: render link preview

### PR DESCRIPTION
**Pull request by ubmit**
# Summary

Solves #131 

* What is the feature? Render link preview when there is a non-image url on the tweet.
* How did you implement the solution? I used the `LinkPreview` component provided by https://github.com/Dhaiwat10/react-link-preview and added a variable named `nonImageUrlChunk` that checks whether there is a non-image url on the tweet or not. With that I'm able to render the component conditionally.

### CODE REVIEW

**Review by sibelius — APPROVED** [review]

**Comment by ubmit** [comment]
@sibelius thanks for the fast review! 🥷 I was still writing the description 😂

**Comment by sibelius** [comment]
image
image
image
image

It breaks in a few cases

I think og is broken on sseraphini.cc

**Comment by ubmit** [comment]
By breaking you mean this, for instance? 
image

If so, my first guess is that the metadata isn't there for the links where this happen. We can add a fallback image https://github.com/dhaiwat10/react-link-preview/blob/HEAD/src/components/LinkPreview/LinkPreview.stories.tsx#L53 though. How that sounds?

**Comment by sibelius** [comment]
2 things

- if metadata is missing do not render anything
- try to fix metadata for this repo

**Comment by sibelius** [comment]
we can improve in next pull requests

thanks for the contribution

**Comment by ubmit** [comment]
My pleasure!

**Pull request merged**
